export default ({ env }) => [
  'strapi::logger',
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:', 'pub-9ff861aa5ec14578b94dca9cd38e3f70.r2.dev'],
          'img-src': [
            "'self'",
            'data:',
            'blob:',
            'market-assets.strapi.io',
            '*.r2.cloudflarestorage.com',
            'pub-9ff861aa5ec14578b94dca9cd38e3f70.r2.dev',
            'https://pub-9ff861aa5ec14578b94dca9cd38e3f70.r2.dev',
            'https://media.gheraltatours.com',
            'https://media.gheraltaadventures.com',
            'https://media.abuneyemata.com',
            '*.gheraltatours.com',
            '*.gheraltaadventures.com',
            '*.abuneyemata.com',
          ],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            'market-assets.strapi.io',
            '*.r2.cloudflarestorage.com',
            'pub-9ff861aa5ec14578b94dca9cd38e3f70.r2.dev',
            'https://pub-9ff861aa5ec14578b94dca9cd38e3f70.r2.dev',
            'https://media.gheraltatours.com',
            'https://media.gheraltaadventures.com',
            'https://media.abuneyemata.com',
            '*.gheraltatours.com',
            '*.gheraltaadventures.com',
            '*.abuneyemata.com',
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  {
    name: 'strapi::cors',
    config: {
      origin: ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:1337'],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
      headers: ['Content-Type', 'Authorization', 'Origin', 'Accept'],
      keepHeaderOnError: true,
    },
  },
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];